version_name: '1.1.7'
version_code: '7'
download_android: 'http://static.lesmarthome.com/smartmattress/SmartMattress-1.1.7.apk'
download_ios: 'https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=1178654680&mt=8'
